### ISSUE TITLE
Tamoko has no spells

### ISSUE THREAD

**Issue by dark0dave** [RoxanneSHS/Tamoko#1]
It looks like Tamoko only has the spells she does as a creature. Additionally, her exp is too high, probably should be set based on what the current party has.

Too high exp:
![high_exp](https://github.com/RoxanneSHS/Tamoko/assets/52840419/d0fd9711-4375-4c84-9f36-e91dd558b390)

No spells:
![image](https://github.com/RoxanneSHS/Tamoko/assets/52840419/87e32944-16fc-43cb-9a9f-49feebdd218f)
![image](https://github.com/RoxanneSHS/Tamoko/assets/52840419/66aaef11-512d-4799-b6ee-9b46e81b8f50)
![image](https://github.com/RoxanneSHS/Tamoko/assets/52840419/2ce94057-f668-451f-9a3d-40ed57125ea1)

**Comment by RoxanneSHS** [comment]
This is how the original Bioware creature is designed. The mod takes it off from there - and this is the intention. Maybe the story you get from her dialogues if she joins explains it a bit (priestess of a dead deity and follower of a want-to-be-god who failed).
The original game characters did not always follow the game' s own rules, so much is true.

**Comment by dark0dave** [comment]
> This is how the original Bioware creature is designed. The mod takes it off from there - and this is the intention. Maybe the story you get from her dialogues if she joins explains it a bit (priestess of a dead deity and follower of a want-to-be-god who failed). The original game characters did not always follow the game' s own rules, so much is true.

Shouldn't we fix that, if we want the player character to use her? You can assign specific spells that are relevant?

If you feel that is not inline with the character, no worries, feel free to close this issue.
